const data = {
    man: {
      1: {
        brand: "Armani",
        model: "Acqua di Gio",
        quantity: "100ml",
        description: "A fresh and aquatic fragrance for men.",
        Year: 2010,
        Type: "eau de parfum",
      },
      2: {
        brand: "Chanel",
        model: "Bleu de Chanel",
        quantity: "50ml",
        description: "A woody and aromatic fragrance for men.",
        Year: 2010,
        Type: "eau de toilette",
      },
      3: {
        brand: "Dior",
        model: "Sauvage",
        quantity: "60ml",
        description: "A bold and magnetic fragrance for men.",
        Year: 2015,
        Type: "eau de parfum",
      },
      4: {
        brand: "Versace",
        model: "Dylan Blue",
        quantity: "100ml",
        description: "A sophisticated and sensual fragrance for men.",
        Year: 2016,
        Type: "eau de toilette",
      },
      5: {
        brand: "Gucci",
        model: "Guilty",
        quantity: "90ml",
        description: "A daring and seductive fragrance for men.",
        Year: 2011,
        Type: "eau de parfum",
      },
      6: {
        brand: "Hugo Boss",
        model: "Boss Bottled",
        quantity: "100ml",
        description: "A classic and versatile fragrance for men.",
        Year: 1998,
        Type: "eau de toilette",
      },
      7: {
        brand: "Calvin Klein",
        model: "Eternity",
        quantity: "50ml",
        description: "A timeless and fresh fragrance for men.",
        Year: 1989,
        Type: "eau de parfum",
      },
      8: {
        brand: "Yves Saint Laurent",
        model: "La Nuit de L'Homme",
        quantity: "60ml",
        description: "A sensual and mysterious fragrance for men.",
        Year: 2009,
        Type: "eau de toilette",
      },
      9: {
        brand: "Paco Rabanne",
        model: "1 Million",
        quantity: "100ml",
        description: "A luxurious and flamboyant fragrance for men.",
        Year: 2008,
        Type: "eau de parfum",
      },
      10: {
        brand: "Bvlgari",
        model: "Bvlgari Man in Black",
        quantity: "90ml",
        description: "An oriental and powerful fragrance for men.",
        Year: 2014,
        Type: "eau de toilette",
      },
      11: {
        brand: "Tom Ford",
        model: "Oud Wood",
        quantity: "50ml",
        description: "A luxurious and exotic fragrance for men.",
        Year: 2007,
        Type: "eau de parfum",
      },
      12: {
        brand: "Jean Paul Gaultier",
        model: "Le Male",
        quantity: "75ml",
        description: "An iconic and bold fragrance for men.",
        Year: 1995,
        Type: "eau de toilette",
      },
      13: {
        brand: "Burberry",
        model: "Mr. Burberry",
        quantity: "100ml",
        description: "A sophisticated and refined fragrance for men.",
        Year: 2016,
        Type: "eau de parfum",
      },
      14: {
        brand: "Dolce & Gabbana",
        model: "The One",
        quantity: "50ml",
        description: "An elegant and charismatic fragrance for men.",
        Year: 2008,
        Type: "eau de toilette",
      },
      15: {
        brand: "Prada",
        model: "L'Homme",
        quantity: "100ml",
        description: "A modern and clean fragrance for men.",
        Year: 2016,
        Type: "eau de parfum",
      },
      16: {
        brand: "Issey Miyake",
        model: "L'Eau d'Issey",
        quantity: "75ml",
        description: "A fresh and timeless fragrance for men.",
        Year: 1994,
        Type: "eau de toilette",
      },
      17: {
        brand: "Ralph Lauren",
        model: "Polo Red",
        quantity: "125ml",
        description: "A fiery and energizing fragrance for men.",
        Year: 2013,
        Type: "eau de parfum",
      },
      18: {
        brand: "Guerlain",
        model: "Habit Rouge",
        quantity: "100ml",
        description: "A classic and sophisticated fragrance for men.",
        Year: 1965,
        Type: "eau de toilette",
      },
      19: {
        brand: "Giorgio Armani",
        model: "Code",
        quantity: "75ml",
        description: "A seductive and elegant fragrance for men.",
        Year: 2004,
        Type: "eau de parfum",
      },
      20: {
        brand: "Montblanc",
        model: "Legend",
        quantity: "100ml",
        description: "A charismatic and powerful fragrance for men.",
        Year: 2011,
        Type: "eau de toilette",
      },
      21: {
        brand: "Yves Saint Laurent",
        model: "Kouros",
        quantity: "100ml",
        description: "A bold and aromatic fragrance for men.",
        Year: 1981,
        Type: "eau de parfum",
      },
      22: {
        brand: "Paco Rabanne",
        model: "Invictus",
        quantity: "50ml",
        description: "An invigorating and sporty fragrance for men.",
        Year: 2013,
        Type: "eau de toilette",
      },
      23: {
        brand: "Dior",
        model: "Fahrenheit",
        quantity: "100ml",
        description: "A unique and bold fragrance for men.",
        Year: 1988,
        Type: "eau de parfum",
      },
      24: {
        brand: "Hermes",
        model: "Terre d'Hermes",
        quantity: "75ml",
        description: "An earthy and woody fragrance for men.",
        Year: 2006,
        Type: "eau de toilette",
      },
      25: {
        brand: "Acqua di Parma",
        model: "Colonia",
        quantity: "100ml",
        description: "A classic and refined fragrance for men.",
        Year: 1916,
        Type: "eau de parfum",
      },
      26: {
        brand: "Cartier",
        model: "Declaration",
        quantity: "50ml",
        description: "A fresh and elegant fragrance for men.",
        Year: 1998,
        Type: "eau de toilette",
      },
      27: {
        brand: "Jean Paul Gaultier",
        model: "Ultra Male",
        quantity: "125ml",
        description: "An intense and irresistible fragrance for men.",
        Year: 2015,
        Type: "eau de parfum",
      },
      28: {
        brand: "Givenchy",
        model: "Gentleman",
        quantity: "100ml",
        description: "A modern and sophisticated fragrance for men.",
        Year: 2017,
        Type: "eau de toilette",
      },
      29: {
        brand: "Tom Ford",
        model: "Noir de Noir",
        quantity: "50ml",
        description: "A luxurious and opulent fragrance for men.",
        Year: 2007,
        Type: "eau de parfum",
      },
      30: {
        brand: "Dolce & Gabbana",
        model: "Light Blue",
        quantity: "100ml",
        description: "A fresh and citrusy fragrance for men.",
        Year: 2007,
        Type: "eau de toilette",
      },
    },
    woman: {
      1: {
        brand: "Chanel",
        model: "Coco Mademoiselle",
        quantity: "100ml",
        description: "An elegant and sophisticated scent for women.",
        Year: 2001,
        Type: "eau de parfum",
      },
      2: {
        brand: "Dior",
        model: "J'adore",
        quantity: "50ml",
        description: "A floral and feminine fragrance for women.",
        Year: 1999,
        Type: "eau de toilette",
      },
      3: {
        brand: "Gucci",
        model: "Bloom",
        quantity: "60ml",
        description: "A rich and floral fragrance for women.",
        Year: 2017,
        Type: "eau de parfum",
      },
      4: {
        brand: "Yves Saint Laurent",
        model: "Black Opium",
        quantity: "90ml",
        description: "An addictive and daring fragrance for women.",
        Year: 2014,
        Type: "eau de toilette",
      },
      5: {
        brand: "Dolce & Gabbana",
        model: "Dolce",
        quantity: "75ml",
        description: "A delicate and romantic fragrance for women.",
        Year: 2014,
        Type: "eau de parfum",
      },
      6: {
        brand: "Prada",
        model: "Candy",
        quantity: "80ml",
        description: "A playful and sweet fragrance for women.",
        Year: 2011,
        Type: "eau de toilette",
      },
      7: {
        brand: "Burberry",
        model: "My Burberry",
        quantity: "90ml",
        description: "A luxurious and floral fragrance for women.",
        Year: 2014,
        Type: "eau de parfum",
      },
      8: {
        brand: "Givenchy",
        model: "Very Irrésistible",
        quantity: "75ml",
        description: "An energetic and floral fragrance for women.",
        Year: 2003,
        Type: "eau de toilette",
      },
      9: {
        brand: "Tom Ford",
        model: "Black Orchid",
        quantity: "50ml",
        description: "A luxurious and sensual fragrance for women.",
        Year: 2006,
        Type: "eau de parfum",
      },
      10: {
        brand: "Marc Jacobs",
        model: "Daisy",
        quantity: "100ml",
        description: "A fresh and youthful fragrance for women.",
        Year: 2007,
        Type: "eau de toilette",
      },
      11: {
        brand: "Guerlain",
        model: "Mon Guerlain",
        quantity: "90ml",
        description: "A mesmerizing and sensual fragrance for women.",
        Year: 2017,
        Type: "eau de parfum",
      },
      12: {
        brand: "Versace",
        model: "Bright Crystal",
        quantity: "90ml",
        description: "A sparkling and floral fragrance for women.",
        Year: 2006,
        Type: "eau de toilette",
      },
      13: {
        brand: "Chloé",
        model: "Chloé",
        quantity: "75ml",
        description: "A romantic and timeless fragrance for women.",
        Year: 2008,
        Type: "eau de parfum",
      },
      14: {
        brand: "Michael Kors",
        model: "Wonderlust",
        quantity: "100ml",
        description: "A captivating and exotic fragrance for women.",
        Year: 2016,
        Type: "eau de toilette",
      },
      15: {
        brand: "Estée Lauder",
        model: "Modern Muse",
        quantity: "50ml",
        description: "A confident and alluring fragrance for women.",
        Year: 2013,
        Type: "eau de parfum",
      },
      16: {
        brand: "Ralph Lauren",
        model: "Romance",
        quantity: "100ml",
        description: "A classic and elegant fragrance for women.",
        Year: 1998,
        Type: "eau de toilette",
      },
      17: {
        brand: "Jimmy Choo",
        model: "Jimmy Choo",
        quantity: "60ml",
        description: "A glamorous and seductive fragrance for women.",
        Year: 2011,
        Type: "eau de parfum",
      },
      18: {
        brand: "Kenzo",
        model: "Flower by Kenzo",
        quantity: "100ml",
        description: "A poetic and delicate fragrance for women.",
        Year: 2000,
        Type: "eau de toilette",
      },
      19: {
        brand: "Yves Saint Laurent",
        model: "Opium",
        quantity: "90ml",
        description: "An iconic and spicy fragrance for women.",
        Year: 1977,
        Type: "eau de parfum",
      },
      20: {
        brand: "Bvlgari",
        model: "Omnia Crystalline",
        quantity: "65ml",
        description: "A luminous and fresh fragrance for women.",
        Year: 2005,
        Type: "eau de toilette",
      },
      21: {
        brand: "Juicy Couture",
        model: "Viva La Juicy",
        quantity: "100ml",
        description: "A playful and flirtatious fragrance for women.",
        Year: 2008,
        Type: "eau de parfum",
      },
      22: {
        brand: "Dolce & Gabbana",
        model: "The One",
        quantity: "75ml",
        description: "A warm and luxurious fragrance for women.",
        Year: 2006,
        Type: "eau de toilette",
      },
      23: {
        brand: "Mugler",
        model: "Angel",
        quantity: "50ml",
        description: "A gourmand and iconic fragrance for women.",
        Year: 1992,
        Type: "eau de parfum",
      },
      24: {
        brand: "Estée Lauder",
        model: "Pleasures",
        quantity: "100ml",
        description: "A joyful and radiant fragrance for women.",
        Year: 1995,
        Type: "eau de toilette",
      },
      25: {
        brand: "Gucci",
        model: "Guilty",
        quantity: "75ml",
        description: "A daring and seductive fragrance for women.",
        Year: 2010,
        Type: "eau de parfum",
      },
      26: {
        brand: "Chanel",
        model: "Chance",
        quantity: "50ml",
        description: "A youthful and unexpected fragrance for women.",
        Year: 2003,
        Type: "eau de toilette",
      },
      27: {
        brand: "Yves Saint Laurent",
        model: "Mon Paris",
        quantity: "90ml",
        description: "A passionate and modern fragrance for women.",
        Year: 2016,
        Type: "eau de parfum",
      },
      28: {
        brand: "Dior",
        model: "Miss Dior",
        quantity: "50ml",
        description: "A romantic and timeless fragrance for women.",
        Year: 1947,
        Type: "eau de toilette",
      },
      29: {
        brand: "Burberry",
        model: "Brit",
        quantity: "100ml",
        description: "A playful and elegant fragrance for women.",
        Year: 2003,
        Type: "eau de parfum",
      },
      30: {
        brand: "Tom Ford",
        model: "Velvet Orchid",
        quantity: "60ml",
        description: "A luxurious and opulent fragrance for women.",
        Year: 2014,
        Type: "eau de toilette",
      },
    },
    miniature: {
      1: {
        brand: "Armani",
        model: "Acqua di Gio",
        quantity: "5ml",
        description: "A fresh and aquatic miniature fragrance for men.",
        Year: 2010,
        Type: "eau de parfum",
      },
      2: {
        brand: "Chanel",
        model: "Bleu de Chanel",
        quantity: "4ml",
        description: "A woody and aromatic miniature fragrance for men.",
        Year: 2010,
        Type: "eau de toilette",
      },
      3: {
        brand: "Dior",
        model: "Sauvage",
        quantity: "3ml",
        description: "A bold and magnetic miniature fragrance for men.",
        Year: 2015,
        Type: "eau de parfum",
      },
      4: {
        brand: "Versace",
        model: "Dylan Blue",
        quantity: "5ml",
        description: "A sophisticated and sensual miniature fragrance for men.",
        Year: 2016,
        Type: "eau de toilette",
      },
      5: {
        brand: "Gucci",
        model: "Guilty",
        quantity: "4ml",
        description: "A daring and seductive miniature fragrance for men.",
        Year: 2011,
        Type: "eau de parfum",
      },
      6: {
        brand: "Hugo Boss",
        model: "Boss Bottled",
        quantity: "3ml",
        description: "A classic and versatile miniature fragrance for men.",
        Year: 1998,
        Type: "eau de toilette",
      },
      7: {
        brand: "Calvin Klein",
        model: "Eternity",
        quantity: "5ml",
        description: "A timeless and fresh miniature fragrance for men.",
        Year: 1989,
        Type: "eau de parfum",
      },
      8: {
        brand: "Yves Saint Laurent",
        model: "La Nuit de L'Homme",
        quantity: "4ml",
        description: "A sensual and mysterious miniature fragrance for men.",
        Year: 2009,
        Type: "eau de toilette",
      },
      9: {
        brand: "Paco Rabanne",
        model: "1 Million",
        quantity: "3ml",
        description: "A luxurious and flamboyant miniature fragrance for men.",
        Year: 2008,
        Type: "eau de parfum",
      },
      10: {
        brand: "Bvlgari",
        model: "Bvlgari Man in Black",
        quantity: "5ml",
        description: "An oriental and powerful miniature fragrance for men.",
        Year: 2014,
        Type: "eau de toilette",
      },
      11: {
        brand: "Tom Ford",
        model: "Oud Wood",
        quantity: "4ml",
        description: "A luxurious and exotic miniature fragrance for men.",
        Year: 2007,
        Type: "eau de parfum",
      },
      12: {
        brand: "Jean Paul Gaultier",
        model: "Le Male",
        quantity: "3ml",
        description: "An iconic and bold miniature fragrance for men.",
        Year: 1995,
        Type: "eau de toilette",
      },
      13: {
        brand: "Burberry",
        model: "Mr. Burberry",
        quantity: "5ml",
        description: "A sophisticated and refined miniature fragrance for men.",
        Year: 2016,
        Type: "eau de parfum",
      },
      14: {
        brand: "Dolce & Gabbana",
        model: "The One",
        quantity: "4ml",
        description: "An elegant and charismatic miniature fragrance for men.",
        Year: 2008,
        Type: "eau de toilette",
      },
      15: {
        brand: "Prada",
        model: "L'Homme",
        quantity: "3ml",
        description: "A modern and clean miniature fragrance for men.",
        Year: 2016,
        Type: "eau de parfum",
      },
      16: {
        brand: "Issey Miyake",
        model: "L'Eau d'Issey",
        quantity: "5ml",
        description: "A fresh and timeless miniature fragrance for men.",
        Year: 1994,
        Type: "eau de toilette",
      },
      17: {
        brand: "Ralph Lauren",
        model: "Polo Red",
        quantity: "4ml",
        description: "A fiery and energizing miniature fragrance for men.",
        Year: 2013,
        Type: "eau de parfum",
      },
      18: {
        brand: "Guerlain",
        model: "Habit Rouge",
        quantity: "3ml",
        description: "A classic and sophisticated miniature fragrance for men.",
        Year: 1965,
        Type: "eau de toilette",
      },
      19: {
        brand: "Giorgio Armani",
        model: "Code",
        quantity: "5ml",
        description: "A seductive and elegant miniature fragrance for men.",
        Year: 2004,
        Type: "eau de parfum",
      },
      20: {
        brand: "Montblanc",
        model: "Legend",
        quantity: "4ml",
        description: "A charismatic and powerful miniature fragrance for men.",
        Year: 2011,
        Type: "eau de toilette",
      },
      21: {
        brand: "Dior",
        model: "Fahrenheit",
        quantity: "3ml",
        description: "An explosive and bold miniature fragrance for men.",
        Year: 1988,
        Type: "eau de parfum",
      },
      22: {
        brand: "Jimmy Choo",
        model: "Jimmy Choo Man",
        quantity: "5ml",
        description: "A modern and urban miniature fragrance for men.",
        Year: 2014,
        Type: "eau de toilette",
      },
      23: {
        brand: "Chanel",
        model: "Allure Homme Sport",
        quantity: "4ml",
        description: "A dynamic and fresh miniature fragrance for men.",
        Year: 2004,
        Type: "eau de parfum",
      },
      24: {
        brand: "Yves Saint Laurent",
        model: "Kouros",
        quantity: "3ml",
        description: "A powerful and masculine miniature fragrance for men.",
        Year: 1981,
        Type: "eau de toilette",
      },
      25: {
        brand: "Gucci",
        model: "Guilty Absolute",
        quantity: "5ml",
        description: "A mysterious and intense miniature fragrance for men.",
        Year: 2017,
        Type: "eau de parfum",
      },
      26: {
        brand: "Paco Rabanne",
        model: "Invictus",
        quantity: "4ml",
        description: "An exhilarating and fresh miniature fragrance for men.",
        Year: 2013,
        Type: "eau de toilette",
      },
      27: {
        brand: "Versace",
        model: "Eros",
        quantity: "3ml",
        description: "A passionate and seductive miniature fragrance for men.",
        Year: 2012,
        Type: "eau de parfum",
      },
      28: {
        brand: "Dolce & Gabbana",
        model: "Light Blue",
        quantity: "5ml",
        description: "A breezy and fresh miniature fragrance for men.",
        Year: 2007,
        Type: "eau de toilette",
      },
      29: {
        brand: "Bvlgari",
        model: "Aqva",
        quantity: "4ml",
        description: "An aquatic and vibrant miniature fragrance for men.",
        Year: 2005,
        Type: "eau de parfum",
      },
      30: {
        brand: "Acqua di Parma",
        model: "Colonia",
        quantity: "3ml",
        description: "A classic and refined miniature fragrance for men.",
        Year: 1916,
        Type: "eau de toilette",
      },
    },
    samples: {
      1: {
        brand: "Chanel",
        model: "Coco Mademoiselle",
        quantity: "1.5ml",
        description: "An elegant and sophisticated sample-sized perfume for women.",
        Year: 2001,
        Type: "eau de parfum",
      },
      2: {
        brand: "Dior",
        model: "J'adore",
        quantity: "2ml",
        description: "A floral and feminine sample-sized perfume for women.",
        Year: 1999,
        Type: "eau de toilette",
      },
      3: {
        brand: "Gucci",
        model: "Bloom",
        quantity: "1.2ml",
        description: "A rich and floral sample-sized perfume for women.",
        Year: 2017,
        Type: "eau de parfum",
      },
      4: {
        brand: "Yves Saint Laurent",
        model: "Black Opium",
        quantity: "1ml",
        description: "An addictive and daring sample-sized perfume for women.",
        Year: 2014,
        Type: "eau de toilette",
      },
      5: {
        brand: "Dolce & Gabbana",
        model: "Dolce",
        quantity: "1.5ml",
        description: "A delicate and romantic sample-sized perfume for women.",
        Year: 2014,
        Type: "eau de parfum",
      },
      6: {
        brand: "Prada",
        model: "Candy",
        quantity: "2ml",
        description: "A playful and sweet sample-sized perfume for women.",
        Year: 2011,
        Type: "eau de toilette",
      },
      7: {
        brand: "Burberry",
        model: "My Burberry",
        quantity: "1.2ml",
        description: "A luxurious and floral sample-sized perfume for women.",
        Year: 2014,
        Type: "eau de parfum",
      },
      8: {
        brand: "Givenchy",
        model: "Very Irrésistible",
        quantity: "1ml",
        description: "An energetic and floral sample-sized perfume for women.",
        Year: 2003,
        Type: "eau de toilette",
      },
      9: {
        brand: "Tom Ford",
        model: "Black Orchid",
        quantity: "1.5ml",
        description: "A luxurious and sensual sample-sized perfume for women.",
        Year: 2006,
        Type: "eau de parfum",
      },
      10: {
        brand: "Marc Jacobs",
        model: "Daisy",
        quantity: "2ml",
        description: "A fresh and youthful sample-sized perfume for women.",
        Year: 2007,
        Type: "eau de toilette",
      },
      11: {
        brand: "Guerlain",
        model: "Mon Guerlain",
        quantity: "1.2ml",
        description: "A mesmerizing and sensual sample-sized perfume for women.",
        Year: 2017,
        Type: "eau de parfum",
      },
      12: {
        brand: "Versace",
        model: "Bright Crystal",
        quantity: "1ml",
        description: "A sparkling and floral sample-sized perfume for women.",
        Year: 2006,
        Type: "eau de toilette",
      },
      13: {
        brand: "Chloé",
        model: "Chloé",
        quantity: "1.5ml",
        description: "A romantic and timeless sample-sized perfume for women.",
        Year: 2008,
        Type: "eau de parfum",
      },
      14: {
        brand: "Michael Kors",
        model: "Wonderlust",
        quantity: "2ml",
        description: "A captivating and exotic sample-sized perfume for women.",
        Year: 2016,
        Type: "eau de toilette",
      },
      15: {
        brand: "Estée Lauder",
        model: "Modern Muse",
        quantity: "1.2ml",
        description: "A confident and alluring sample-sized perfume for women.",
        Year: 2013,
        Type: "eau de parfum",
      },
      16: {
        brand: "Ralph Lauren",
        model: "Romance",
        quantity: "1ml",
        description: "A classic and elegant sample-sized perfume for women.",
        Year: 1998,
        Type: "eau de toilette",
      },
      17: {
        brand: "Jimmy Choo",
        model: "Jimmy Choo",
        quantity: "1.5ml",
        description: "A glamorous and seductive sample-sized perfume for women.",
        Year: 2011,
        Type: "eau de parfum",
      },
      18: {
        brand: "Kenzo",
        model: "Flower by Kenzo",
        quantity: "2ml",
        description: "A poetic and delicate sample-sized perfume for women.",
        Year: 2000,
        Type: "eau de toilette",
      },
      19: {
        brand: "Yves Saint Laurent",
        model: "Opium",
        quantity: "1.2ml",
        description: "An iconic and spicy sample-sized perfume for women.",
        Year: 1977,
        Type: "eau de parfum",
      },
      20: {
        brand: "Bvlgari",
        model: "Omnia Crystalline",
        quantity: "1ml",
        description: "A luminous and fresh sample-sized perfume for women.",
        Year: 2005,
        Type: "eau de toilette",
      },
      21: {
        brand: "Juicy Couture",
        model: "Viva La Juicy",
        quantity: "1.5ml",
        description: "A playful and flirtatious sample-sized perfume for women.",
        Year: 2008,
        Type: "eau de parfum",
      },
      22: {
        brand: "Dolce & Gabbana",
        model: "The One",
        quantity: "2ml",
        description: "A warm and luxurious sample-sized perfume for women.",
        Year: 2006,
        Type: "eau de toilette",
      },
      23: {
        brand: "Mugler",
        model: "Angel",
        quantity: "1.2ml",
        description: "A gourmand and iconic sample-sized perfume for women.",
        Year: 1992,
        Type: "eau de parfum",
      },
      24: {
        brand: "Estée Lauder",
        model: "Pleasures",
        quantity: "1ml",
        description: "A joyful and radiant sample-sized perfume for women.",
        Year: 1995,
        Type: "eau de toilette",
      },
      25: {
        brand: "Gucci",
        model: "Guilty",
        quantity: "1.5ml",
        description: "A daring and seductive sample-sized perfume for women.",
        Year: 2010,
        Type: "eau de parfum",
      },
      26: {
        brand: "Chanel",
        model: "Chance",
        quantity: "2ml",
        description: "A youthful and unexpected sample-sized perfume for women.",
        Year: 2003,
        Type: "eau de toilette",
      },
      27: {
        brand: "Yves Saint Laurent",
        model: "Mon Paris",
        quantity: "1.2ml",
        description: "A passionate and modern sample-sized perfume for women.",
        Year: 2016,
        Type: "eau de parfum",
      },
      28: {
        brand: "Dior",
        model: "Miss Dior",
        quantity: "1ml",
        description: "A romantic and timeless sample-sized perfume for women.",
        Year: 1947,
        Type: "eau de toilette",
      },
      29: {
        brand: "Burberry",
        model: "Brit",
        quantity: "1.5ml",
        description: "A playful and elegant sample-sized perfume for women.",
        Year: 2003,
        Type: "eau de parfum",
      },
      30: {
        brand: "Tom Ford",
        model: "Velvet Orchid",
        quantity: "2ml",
        description: "A luxurious and opulent sample-sized perfume for women.",
        Year: 2014,
        Type: "eau de toilette",
      },
    },
    vintage: {
      1: {
        brand: "Chanel",
        model: "No. 5",
        quantity: "30ml",
        description: "An iconic and timeless vintage fragrance for women.",
        Year: 1921,
        Type: "parfum",
      },
      2: {
        brand: "Dior",
        model: "Miss Dior",
        quantity: "25ml",
        description: "A classic and elegant vintage fragrance for women.",
        Year: 1947,
        Type: "parfum",
      },
      3: {
        brand: "Guerlain",
        model: "Shalimar",
        quantity: "35ml",
        description: "A seductive and oriental vintage fragrance for women.",
        Year: 1925,
        Type: "parfum",
      },
      4: {
        brand: "Yves Saint Laurent",
        model: "Opium",
        quantity: "20ml",
        description: "A rich and exotic vintage fragrance for women.",
        Year: 1977,
        Type: "parfum",
      },
      5: {
        brand: "Givenchy",
        model: "L'Interdit",
        quantity: "30ml",
        description: "A forbidden and sophisticated vintage fragrance for women.",
        Year: 1957,
        Type: "parfum",
      },
      6: {
        brand: "Estée Lauder",
        model: "Youth Dew",
        quantity: "25ml",
        description: "A warm and captivating vintage fragrance for women.",
        Year: 1953,
        Type: "parfum",
      },
      7: {
        brand: "Chloé",
        model: "Chloé",
        quantity: "35ml",
        description: "A feminine and romantic vintage fragrance for women.",
        Year: 1975,
        Type: "parfum",
      },
      8: {
        brand: "Guerlain",
        model: "Mitsouko",
        quantity: "20ml",
        description: "A mysterious and sensual vintage fragrance for women.",
        Year: 1919,
        Type: "parfum",
      },
      9: {
        brand: "Nina Ricci",
        model: "L'Air du Temps",
        quantity: "30ml",
        description: "A floral and graceful vintage fragrance for women.",
        Year: 1948,
        Type: "parfum",
      },
      10: {
        brand: "Dior",
        model: "Poison",
        quantity: "25ml",
        description: "A bold and provocative vintage fragrance for women.",
        Year: 1985,
        Type: "parfum",
      },
      11: {
        brand: "Chanel",
        model: "Coco",
        quantity: "35ml",
        description: "A luxurious and sophisticated vintage fragrance for women.",
        Year: 1984,
        Type: "parfum",
      },
      12: {
        brand: "Guerlain",
        model: "Vol de Nuit",
        quantity: "20ml",
        description: "A romantic and enchanting vintage fragrance for women.",
        Year: 1933,
        Type: "parfum",
      },
      13: {
        brand: "Estée Lauder",
        model: "White Linen",
        quantity: "30ml",
        description: "A fresh and crisp vintage fragrance for women.",
        Year: 1978,
        Type: "parfum",
      },
      14: {
        brand: "Yves Saint Laurent",
        model: "Rive Gauche",
        quantity: "25ml",
        description: "A chic and iconic vintage fragrance for women.",
        Year: 1971,
        Type: "parfum",
      },
      15: {
        brand: "Dior",
        model: "J'adore",
        quantity: "35ml",
        description: "A glamorous and opulent vintage fragrance for women.",
        Year: 1999,
        Type: "parfum",
      },
      16: {
        brand: "Guerlain",
        model: "L'Heure Bleue",
        quantity: "20ml",
        description: "A romantic and melancholic vintage fragrance for women.",
        Year: 1912,
        Type: "parfum",
      },
      17: {
        brand: "Chanel",
        model: "Cristalle",
        quantity: "30ml",
        description: "A refreshing and elegant vintage fragrance for women.",
        Year: 1974,
        Type: "parfum",
      },
      18: {
        brand: "Nina Ricci",
        model: "Nina",
        quantity: "25ml",
        description: "A sweet and playful vintage fragrance for women.",
        Year: 2006,
        Type: "parfum",
      },
      19: {
        brand: "Guerlain",
        model: "Champs-Élysées",
        quantity: "35ml",
        description: "A joyful and radiant vintage fragrance for women.",
        Year: 1996,
        Type: "parfum",
      },
      20: {
        brand: "Estée Lauder",
        model: "Pleasures",
        quantity: "20ml",
        description: "A delightful and carefree vintage fragrance for women.",
        Year: 1995,
        Type: "parfum",
      },
      21: {
        brand: "Yves Saint Laurent",
        model: "Nu",
        quantity: "30ml",
        description: "A modern and daring vintage fragrance for women.",
        Year: 2001,
        Type: "parfum",
      },
      22: {
        brand: "Chanel",
        model: "Gabrielle",
        quantity: "25ml",
        description: "An exuberant and radiant vintage fragrance for women.",
        Year: 2017,
        Type: "parfum",
      },
      23: {
        brand: "Guerlain",
        model: "Jicky",
        quantity: "35ml",
        description: "A groundbreaking and androgynous vintage fragrance for women.",
        Year: 1889,
        Type: "parfum",
      },
      24: {
        brand: "Estée Lauder",
        model: "Knowing",
        quantity: "20ml",
        description: "A sensual and powerful vintage fragrance for women.",
        Year: 1988,
        Type: "parfum",
      },
      25: {
        brand: "Nina Ricci",
        model: "Luna",
        quantity: "30ml",
        description: "A mysterious and enchanting vintage fragrance for women.",
        Year: 2016,
        Type: "parfum",
      },
      26: {
        brand: "Yves Saint Laurent",
        model: "Mon Paris",
        quantity: "25ml",
        description: "A passionate and modern vintage fragrance for women.",
        Year: 2016,
        Type: "parfum",
      },
      27: {
        brand: "Chanel",
        model: "Chance",
        quantity: "35ml",
        description: "A youthful and lively vintage fragrance for women.",
        Year: 2003,
        Type: "parfum",
      },
      28: {
        brand: "Guerlain",
        model: "Après L'Ondée",
        quantity: "20ml",
        description: "A poetic and dreamy vintage fragrance for women.",
        Year: 1906,
        Type: "parfum",
      },
      29: {
        brand: "Estée Lauder",
        model: "Modern Muse",
        quantity: "30ml",
        description: "A confident and empowering vintage fragrance for women.",
        Year: 2013,
        Type: "parfum",
      },
      30: {
        brand: "Yves Saint Laurent",
        model: "Black Opium",
        quantity: "25ml",
        description: "A bold and electrifying vintage fragrance for women.",
        Year: 2014,
        Type: "parfum",
      },
    },
  };

export default data;